target 'iosApp' do
  use_frameworks!
  platform :ios, '13.0'
  pod 'shared', :path => '../shared'
  
  pod 'KMPNativeCoroutinesRxSwift', '~> 1.0.0-ALPHA-11'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
